name: Android Unsigned APK Build

on:
  # 可根据需求修改触发条件，这里配置为推送到 main 分支和手动触发
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-unsigned-apk:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Java 环境
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      # 给 gradlew 脚本添加执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 运行 Gradle 构建任务，跳过签名步骤
      - name: Build unsigned APK
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'current'
          arguments: assembleRelease -x :app:packageRelease

      # 查找并移动生成的未签名 APK 文件
      - name: Move unsigned APK
        run: |
          apk_file=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          if [ -n "$apk_file" ]; then
            mv $apk_file unsigned_app.apk
          else
            echo "未找到 APK 文件"
            
          fi

      # 上传未签名的 APK 作为工作流的产物
      - name: Upload unsigned APK
        uses: actions/upload-artifact@v3
        with:
          name: unsigned-apk
          path: unsigned_app.apk
